version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: do-it
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./logs:/app/logs
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db-data:
